---
# tasks file for devstack_compute
- name: set nodepool facts
  set_fact:
    zuul:
      projects: "{{ compute_projects }}"
      project: "{{ compute_project }}"

- name:  enable_ceph
  when: "compute_enable_ceph | bool"
  set_fact:
    compute_devstack_plugins:
      devstack-plugin-ceph: "{{ git_base }}/openstack/devstack-plugin-ceph"

- name: template local.conf
  include_role:
    name: write-devstack-local-conf
  vars:
    devstack_base_dir: '{{repos_dir}}'
    devstack_localrc: '{{ compute_localrc | combine(compute_localrc_extra) }}'
    devstack_local_conf: '{{ compute_local_conf | combine(compute_local_conf_extra) }}'
    devstack_services: '{{ compute_services | combine(compute_services_extra) }}'
    devstack_plugins: '{{compute_devstack_plugins}}'

- name: Run devstack on the compute
  when: "run_devstack | default(true) | bool" 
  include_role:
    name: run-devstack
  vars:
    devstack_base_dir: '{{repos_dir}}'
