---
# tasks file for devstack_contoller
- name: set nodepool facts
  set_fact:
    zuul:
      projects: "{{ controller_projects }}"
      project: "{{ controller_project }}"

- name: vdpa pci whitelist and filter
  when: "configure_vdpa"
  set_fact:
    vdpa_local_conf:
      post_config:
        $NOVA_CONF:
          filter_scheduler:
            enabled_filters: "ComputeFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,SameHostFilter,DifferentHostFilter,PciPassthroughFilter,NUMATopologyFilter"
        $NOVA_CPU_CONF:
          pci:
            passthrough_whitelist: '{"vendor_id":"15b3", "product_id": "101e", "physical_network": null}'

- name:  enable_ceph
  when: "enable_ceph | bool"
  set_fact:
    controller_devstack_plugins:
      devstack-plugin-ceph: "{{ git_base }}/openstack/devstack-plugin-ceph"

- name: template local.conf
  include_role:
    name: write-devstack-local-conf
  vars:
    devstack_base_dir: '{{ repos_dir }}'
    devstack_localrc: '{{ controller_localrc | combine(controller_localrc_extra) }}'
    devstack_local_conf: '{{ controller_local_conf | combine(vdpa_local_conf | default({})) | combine(controller_local_conf_extra) }}'
    devstack_services: '{{ controller_services | combine(controller_services_extra) }}'
    devstack_plugins:  '{{ controller_devstack_plugins }}'

- name: Run devstack on the controller
  when: "run_devstack | default(true) | bool" 
  include_role:
    name: run-devstack
  vars:
    devstack_base_dir: '{{repos_dir}}'
