---
- name: Apply role devstack_common
  hosts: all
  roles:
    - devstack_common
    - { role: validate-host, when:"validate_hosts | default(false) | bool" }
    - multi-node-known-hosts
    - multi-node-bridge
    - ensure-pip
