---
- name: "execute devstack_common on all hosts"
  import_playbook: ../../ansible/devstack_common.yaml 
- name: "deploy devstack controller"
  import_playbook: ../../ansible/devstack_controller.yaml

- name: sync controller data to subnodes
  hosts: all
  tasks:
    - name: set nodepool facts
      set_fact:
        nodepool:
          private_ipv4: "{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"
          public_ipv4: "{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"
        zuul:
          executor:
            log_root: /tmp/zuul_logs
            work_root: /tmp/work_root

- name: sync controller data to subnodes
  hosts: all
  roles:
    - role:  sync-devstack-data

#- name: sync ceph configs to subnodes
#  hosts: subnode
#  roles:
#    - role: sync-controller-ceph-conf-and-keys
#      ignore_errors: yes

- name: "deploy devstack compute(s)"
  import_playbook: ../../ansible/devstack_compute.yaml
